export const SERVER_MESSAGE_TYPE = {
  USER_JOINED: 'A',
  CHAT_MESSAGE: 'B',
  USER_LEFT: 'C',
  CHAT_HISTORY: 'D',
  ERROR: 'E',
  AUTHENTICATED: 'F',
};

export const CLIENT_MESSAGE_TYPE = {
  AUTHENTICATION_REQUEST: 'z',
  CHAT_MESSAGE: 'y',
};
